### ISSUE TITLE
TypeError: Transaction.stat() missing 1 required positional argument: 'db'

### ISSUE THREAD

**Issue by jameshowison** [softcite/mentions_pipeline_notebook#2]
I'm trying to use the notebook in the same way that Shiwon did, but I think I'm running into issues.

```
client = software_mentions_client(config_path="config/config-client.json")
client.annotate_collection("./data", force=True)
```
gives this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 2
      1 client = software_mentions_client(config_path="config/config-client.json")
----> 2 client.annotate_collection("./data", force=True)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/software_mentions_client/client.py:197, in software_mentions_client.annotate_collection(self, data_path, force)
    194 self.env = lmdb.open(envFilePath, map_size=map_size)
    196 with self.env.begin(write=True) as txn:
--> 197     nb_total = txn.stat()['entries']
    198 print("\nnumber of entries to process:", nb_total, "entries\n")
    200 # iterate over the entries in lmdb

TypeError: Transaction.stat() missing 1 required positional argument: 'db'
```

I guess I should look into `software_mentions_client/client.py:197` but it's odd that this was working for Shiwon earlier today.

I think the only difference was that I have Python 3.10.9 installed?  That is the default if you use repo2docker installed from development build, install from source: https://github.com/jupyterhub/repo2docker/#installation

**Comment by kermitt2** [comment]
Normally this `.stat()` call is working and I don't see a problem in `software_mentions_client/client.py:197`.

Maybe the error is misleading. Normally the harvesting should be completed when this error appears. 
Do you see under the data path `notebooks/data/` something like this:

```console
lopez@work:~/mentions_pipeline_notebook$ ll notebooks/data/
total 52K
drwxrwxr-x 13 lopez lopez 4.0K Mar 24 09:56 ./
drwxrwxr-x  6 lopez lopez 4.0K Mar 24 09:59 ../
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 0b/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 16/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 38/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 4c/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 53/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 80/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 ae/
drwxrwxr-x  3 lopez lopez 4.0K Mar 24 09:56 c7/
drwxr-xr-x  2 lopez lopez 4.0K Mar 24 09:56 entries/
drwxr-xr-x  2 lopez lopez 4.0K Mar 24 09:56 entries_software/
-rw-rw-r--  1 lopez lopez    0 Mar  7 18:36 .gitkeep
drwxr-xr-x  2 lopez lopez 4.0K Mar 24 09:56 uuid/
```
`entries` and `uuid` are LMDB created by the harvester and used to store the state of the harvesting task (`entries`) and the mapping between DOI and UUID (`uuid`). `entries_software` is a LMDB to keep track of the software extraction task.
The other directories are the places where the PDF and the extraction are stored, with a directory path based on the UUID. 

(the LMDB stuff and UUID might look overkilling in a notebook, but these modules were designed to process millions of PDF files)

**Comment by jameshowison** [comment]
I think this is something to do with lmdb install on mac M2 arm.  I'm switching to docker and liblmdb-dev installs fine.
